# Generated by Django 5.1.4 on 2026-06-25 04:18

import apps.quotes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_quote_public_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='photo_assessment',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='quote',
            name='public_token',
            field=models.CharField(default=apps.quotes.models._gen_public_token, max_length=40, unique=True),
        ),
    ]
