# Generated by Django 5.1.4 on 2026-04-29 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('trade', models.CharField(choices=[('hvac', 'HVAC & Plumbing'), ('windows', 'Windows & Doors'), ('solar', 'Solar & Roofing'), ('renovation', 'Energy Renovation'), ('general', 'General Contractor')], default='general', max_length=32)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('phone_number', models.CharField(blank=True, help_text='Public business line', max_length=32)),
                ('voice_persona', models.CharField(default='Mary', help_text='Display name for the AI receptionist', max_length=64)),
                ('knowledge_base', models.TextField(blank=True, help_text='Pricing rules, FAQ, service area — fed to the LLM as system prompt context')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Businesses',
            },
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('phone', 'Phone'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('chat', 'Web Chat')], max_length=16)),
                ('address', models.CharField(help_text='phone number, email, etc.', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='core.business')),
            ],
            options={
                'unique_together': {('business', 'kind', 'address')},
            },
        ),
    ]
