# Generated by Django 5.1.4 on 2026-05-01 10:08

import apps.core.crypto
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_business_anthropic_api_key_business_openai_api_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='anthropic_api_key',
            field=apps.core.crypto.EncryptedCharField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='business',
            name='openai_api_key',
            field=apps.core.crypto.EncryptedCharField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='business',
            name='twilio_account_sid',
            field=apps.core.crypto.EncryptedCharField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='business',
            name='twilio_auth_token',
            field=apps.core.crypto.EncryptedCharField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='business',
            name='vapi_api_key',
            field=apps.core.crypto.EncryptedCharField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='business',
            name='vapi_phone_number_id',
            field=apps.core.crypto.EncryptedCharField(blank=True, default=''),
        ),
    ]
