# Generated by Django 5.1.4 on 2026-05-02 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_business_anthropic_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='llm_provider',
            field=models.CharField(choices=[('anthropic', 'Anthropic Claude'), ('openai', 'OpenAI GPT')], default='openai', help_text='Which LLM powers Mary and lead extraction.', max_length=16),
        ),
    ]
