# Generated by Django 5.1.4 on 2026-05-02 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_business_llm_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='trade',
            field=models.CharField(choices=[('hvac', 'HVAC & Plumbing'), ('plumbing', 'Plumbing'), ('windows', 'Windows & Doors'), ('roofing', 'Roofing'), ('solar', 'Solar'), ('renovation', 'Energy Renovation'), ('electrical', 'Electrical'), ('garage', 'Garage Doors'), ('landscaping', 'Landscaping'), ('cleaning', 'Cleaning'), ('pest', 'Pest Control'), ('general', 'General Contractor')], default='general', max_length=32),
        ),
    ]
