# Generated by Django 5.2.1 on 2026-05-05 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_business_whatsapp_credentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='vapi_assistant_id',
            field=models.CharField(blank=True, default='', help_text='Vapi assistant ID — when set, name + voice persona changes auto-sync to Vapi.', max_length=128),
        ),
    ]
