from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_business_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="business",
            name="currency",
            field=models.CharField(
                choices=[
                    ("USD", "US Dollar ($)"),
                    ("EUR", "Euro (€)"),
                    ("GBP", "British Pound (£)"),
                    ("CAD", "Canadian Dollar (C$)"),
                    ("AUD", "Australian Dollar (A$)"),
                    ("NZD", "New Zealand Dollar (NZ$)"),
                    ("CHF", "Swiss Franc (CHF)"),
                    ("SEK", "Swedish Krona (kr)"),
                    ("NOK", "Norwegian Krone (kr)"),
                    ("DKK", "Danish Krone (kr)"),
                    ("PLN", "Polish Zloty (zł)"),
                    ("CZK", "Czech Koruna (Kč)"),
                    ("HUF", "Hungarian Forint (Ft)"),
                    ("RON", "Romanian Leu (lei)"),
                    ("TRY", "Turkish Lira (₺)"),
                    ("RUB", "Russian Ruble (₽)"),
                    ("UAH", "Ukrainian Hryvnia (₴)"),
                    ("ILS", "Israeli Shekel (₪)"),
                    ("AED", "UAE Dirham (د.إ)"),
                    ("SAR", "Saudi Riyal (﷼)"),
                    ("QAR", "Qatari Riyal (﷼)"),
                    ("KWD", "Kuwaiti Dinar (د.ك)"),
                    ("BHD", "Bahraini Dinar (.د.ب)"),
                    ("OMR", "Omani Rial (﷼)"),
                    ("JOD", "Jordanian Dinar (د.ا)"),
                    ("EGP", "Egyptian Pound (£)"),
                    ("LBP", "Lebanese Pound (ل.ل)"),
                    ("MAD", "Moroccan Dirham (د.م.)"),
                    ("DZD", "Algerian Dinar (د.ج)"),
                    ("TND", "Tunisian Dinar (د.ت)"),
                    ("ZAR", "South African Rand (R)"),
                    ("NGN", "Nigerian Naira (₦)"),
                    ("KES", "Kenyan Shilling (KSh)"),
                    ("GHS", "Ghanaian Cedi (₵)"),
                    ("ETB", "Ethiopian Birr (Br)"),
                    ("UGX", "Ugandan Shilling (USh)"),
                    ("TZS", "Tanzanian Shilling (TSh)"),
                    ("PKR", "Pakistani Rupee (Rs)"),
                    ("INR", "Indian Rupee (₹)"),
                    ("BDT", "Bangladeshi Taka (৳)"),
                    ("LKR", "Sri Lankan Rupee (Rs)"),
                    ("NPR", "Nepalese Rupee (Rs)"),
                    ("AFN", "Afghan Afghani (؋)"),
                    ("CNY", "Chinese Yuan (¥)"),
                    ("HKD", "Hong Kong Dollar (HK$)"),
                    ("TWD", "Taiwan Dollar (NT$)"),
                    ("JPY", "Japanese Yen (¥)"),
                    ("KRW", "South Korean Won (₩)"),
                    ("SGD", "Singapore Dollar (S$)"),
                    ("MYR", "Malaysian Ringgit (RM)"),
                    ("IDR", "Indonesian Rupiah (Rp)"),
                    ("PHP", "Philippine Peso (₱)"),
                    ("THB", "Thai Baht (฿)"),
                    ("VND", "Vietnamese Dong (₫)"),
                    ("MXN", "Mexican Peso ($)"),
                    ("BRL", "Brazilian Real (R$)"),
                    ("ARS", "Argentine Peso ($)"),
                    ("CLP", "Chilean Peso ($)"),
                    ("COP", "Colombian Peso ($)"),
                    ("PEN", "Peruvian Sol (S/.)"),
                    ("UYU", "Uruguayan Peso ($)"),
                ],
                default="USD",
                help_text="ISO-4217 code Mary quotes prices in and the dashboard formats with.",
                max_length=3,
            ),
        ),
    ]
