# Generated by Django 5.1.4 on 2026-06-25 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_voice_assist_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='do_not_call',
            field=models.TextField(blank=True, default='', help_text='Phone numbers to never call, one per line.'),
        ),
        migrations.AddField(
            model_name='business',
            name='followup_delay_hours',
            field=models.PositiveSmallIntegerField(default=24, help_text='Hours after a quote is drafted to place a follow-up call.'),
        ),
        migrations.AddField(
            model_name='business',
            name='outbound_enabled',
            field=models.BooleanField(default=True, help_text='Master switch for all outbound calling.'),
        ),
        migrations.AddField(
            model_name='business',
            name='quiet_hours_end',
            field=models.PositiveSmallIntegerField(default=8, help_text='No outbound calls before this hour (0-23, business timezone).'),
        ),
        migrations.AddField(
            model_name='business',
            name='quiet_hours_start',
            field=models.PositiveSmallIntegerField(default=21, help_text='No outbound calls at or after this hour (0-23, business timezone).'),
        ),
        migrations.AddField(
            model_name='business',
            name='reactivation_days',
            field=models.PositiveSmallIntegerField(default=30, help_text="A lead becomes eligible for reactivation once it's been cold this many days."),
        ),
        migrations.AddField(
            model_name='business',
            name='speed_to_lead_enabled',
            field=models.BooleanField(default=True, help_text='Auto-call brand-new non-voice leads within a minute of arrival.'),
        ),
        migrations.AlterField(
            model_name='business',
            name='llm_provider',
            field=models.CharField(choices=[('anthropic', 'Anthropic Claude'), ('openai', 'OpenAI GPT')], default='openai', help_text='Which LLM powers the Voice Assist and lead extraction.', max_length=16),
        ),
    ]
