# Generated by Django 5.1.4 on 2026-05-02 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_business_trade'),
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['business', '-created_at'], name='leads_lead_busines_4fd20a_idx'),
        ),
    ]
