export type Dict = Record<string, string>;

export const en: Dict = {
  "nav.features": "Features",
  "nav.how": "How it works",
  "nav.impact": "Impact",
  "nav.industries": "Who it's for",
  "nav.demo": "Live demo",
  "nav.services": "Services",
  "nav.pricing": "Pricing",
  "nav.docs": "How it works",
  "btn.signIn": "Sign in",
  "btn.bookDemo": "Book a demo",
  "btn.explore": "Explore",
  "btn.tellUs": "Tell us about yours",
  "topbar.builtBy": "by",

  "hero.meetStrong": "Hi, I'm Mary.",
  "hero.meetTail": " It answers every call and chases every lead — day and night.",
  "hero.tradesLabel": "Built for any business that lives on the phone —",
  "hero.tradesList": "Home services · Legal · Real estate · Medical · Auto · +more",
  "hero.title1": "Answer every call. Chase every lead.",
  "hero.title2": "Around the clock.",
  "hero.sub": "WorkflowAuth answers your inbound calls and calls leads back — speed-to-lead in seconds, follow-ups, and reactivation — so no opportunity slips through.",
  "story.eyebrow": "What it feels like",
  "story.title1": "One missed call,",
  "story.title2": "turned into a booked job.",
  "story.sub": "Scroll through a single night, the way your Mary actually handles it.",
  "story.s1.beat": "It's late. The phone rings.",
  "story.s1.body": "11:47pm. Your team is offline. The competitor down the road is too. The lead has 30 seconds of patience.",
  "story.s2.beat": "Mary picks up.",
  "story.s2.body": "It greets the caller in your business's voice, asks your qualifying questions, and captures exactly the details you told it to.",
  "story.s3.beat": "Captured. Scored. Booked.",
  "story.s3.body": "It logs a scored, deal-ready lead, books the slot, and — if the caller drops — calls them right back so you never lose the thread.",
  "story.s4.beat": "You wake up booked.",
  "story.s4.body": "Morning coffee. New appointments on the calendar, every lead followed up, the cold ones re-engaged. You haven't touched the phone.",
  "story.s4.foot": "All overnight. No one was awake.",

  "hero.oss": "Open-source · AGPL-3.0",
  "hero.star": "★ Star on GitHub",
  "hero.selfHost": "Self-host or done-for-you setup",

  "features.eyebrow": "Features",
  "features.title": "Configure once. Never lose a lead.",
  "features.sub": "Set your hours, your questions, and your follow-up rules. WorkflowAuth answers inbound calls and dials leads back — speed-to-lead, follow-ups, reactivation, and reminders — for any business.",
  "features.f1.name": "AI Phone Receptionist",
  "features.f1.body": "Never miss a call again. WorkflowAuth picks up every inbound within two rings, captures the details you configured, scores the lead, and books the slot — in a voice you choose, on the script your business runs on.",
  "features.f2.name": "Outbound that chases every lead",
  "features.f2.body": "Speed-to-lead in seconds, scheduled follow-ups, reactivation of cold leads, and appointment reminders — placed automatically or with one tap, so a missed connection never becomes a lost deal.",
  "features.f3.name": "AI Chat Assistant",
  "features.f3.body": "Web chat, SMS, and WhatsApp — same assistant, same memory of the customer. Replies in seconds, hands off to a human only when it should.",
  "features.f4.name": "Configurable lead capture",
  "features.f4.body": "Choose exactly which fields and questions the assistant captures on every call. Each lead comes back scored and ranked so your team works the hottest ones first.",
  "features.f5.name": "AI Knowledge Base",
  "features.f5.body": "Drop in your FAQ, policies, and price list. The assistant answers in your real terms — never invents a price or a promise you don't make.",
  "features.f6.name": "Transfer + post-call digest",
  "features.f6.body": "Set conditions to warm-transfer high-value calls to a human, and get a transcript, summary, and lead score in your inbox after every call.",

  "stats.eyebrow": "Why teams switch",
  "stats.title": "Every missed call is a job your competitor books.",
  "stats.body": "WorkflowAuth picks up every inbound, and when a lead slips by, it calls them right back. Speed-to-lead, follow-ups, and reactivation run on autopilot — it never sleeps and never takes a break.",
  "stats.li1": "Inbound calls answered while your team is offline",
  "stats.li2": "New leads called back within seconds, automatically",
  "stats.li3": "Cold and lost leads reactivated without lifting a finger",
  "stats.card1.num": "24/7",
  "stats.card1.label": "Inbound coverage — every call answered, day or night.",
  "stats.card2.num": "< 60s",
  "stats.card2.label": "Speed-to-lead: new leads get a callback within the minute.",
  "stats.card3.num": "$0",
  "stats.card3.label": "Per missed call. WorkflowAuth books the ones your inbox loses.",

  "flow.eyebrow": "How it flows",
  "flow.title": "How a lead flows through WorkflowAuth.",
  "flow.sub": "Inbound or outbound, fully automated. The customer just gets a quick answer, the right questions, and a booked time slot — and a callback if they ever drop.",

  "convo.eyebrow": "A real conversation",
  "convo.title": "It handles the objection, not just the hello.",
  "convo.sub": "Live thread between your Mary and a customer. Lead qualified, scored, captured, and booked — then followed up automatically.",
  "convo.head.title": "Inbound + Outbound Automation",
  "convo.head.sub": "Captures the lead, scores it, books the slot — then calls back to follow up.",
  "convo.msg1": "Hi, I saw your listing and wanted to ask a few questions before booking.",
  "convo.msg2": "Happy to help. Can I grab your name and the best number to reach you? Then I'll answer anything you need.",
  "convo.msg3": "Sure — it's Jordan, and this number is fine.",
  "convo.msg4Pre": "Perfect, Jordan — you're all set. ",
  "convo.msg4Mid": " I've booked your slot and texted the confirmation. If anything changes, we'll call you back to reschedule.",
  "convo.output": "Output Result",
  "convo.estimate": "Lead #L-291 · scored 92",
  "convo.deal": "Synced · your CRM",
  "convo.survey": "Booked · Tue 9:30 AM",
  "convo.signed": "— Mary",

  "industries.eyebrow": "Who it's for",
  "industries.title": "One assistant. Any business on the phone.",
  "industries.sub": "Your questions, scripts, and follow-up rules are fully editable and vertical-agnostic. Whatever you do, if it runs on phone calls, WorkflowAuth fits.",
  "industries.note": "Plus: not in this list? WorkflowAuth adapts to any business that books work over the phone. ",
  "industries.i1.name": "Home services",
  "industries.i1.body": "After-hours answering, speed-to-lead callbacks, job booking, and appointment reminders.",
  "industries.i2.name": "Legal",
  "industries.i2.body": "Intake screening, conflict-check questions, callback to new matters within minutes.",
  "industries.i3.name": "Real estate",
  "industries.i3.body": "Listing inquiries answered live, instant lead callbacks, showing scheduling.",
  "industries.i4.name": "Medical & dental",
  "industries.i4.body": "New-patient intake, appointment booking, no-show reminders and recalls.",
  "industries.i5.name": "Auto & dealerships",
  "industries.i5.body": "Service scheduling, parts questions, fast follow-up on web and call leads.",
  "industries.i6.name": "Professional services",
  "industries.i6.body": "Consult booking, qualification, reactivation of stale prospects.",
  "industries.i7.name": "Salon & wellness",
  "industries.i7.body": "Booking and rebooking, waitlist callbacks, reminder calls that cut no-shows.",
  "industries.i8.name": "Property management",
  "industries.i8.body": "Tenant and prospect calls, maintenance intake, after-hours coverage.",
  "industries.i9.name": "Trades & contractors",
  "industries.i9.body": "Estimate requests, dispatch triage, follow-up on quotes that went quiet.",

  "config.eyebrow": "Configurable end-to-end",
  "config.title": "Your voice. Your questions. Your CRM. Your hours.",
  "config.body": "Pick from 30+ neural voices in 7 languages. Choose the fields the assistant captures. Connect HubSpot, Pipedrive, Salesforce, or your custom API. Set when it answers, when it transfers, and when it calls leads back. WorkflowAuth runs on your rules.",
  "config.k1.l": "Voice",
  "config.k1.v": "30+ neural · 7 languages",
  "config.k2.l": "Lead capture",
  "config.k2.v": "Your fields · your questions",
  "config.k3.l": "CRM",
  "config.k3.v": "HubSpot · Pipedrive · Salesforce · API",
  "config.k4.l": "Hours",
  "config.k4.v": "Answer · transfer · callback windows",
  "config.k5.l": "Voice cloning",
  "config.k5.v": "Use your owner's voice (optional)",
  "config.k6.l": "Self-host",
  "config.k6.v": "AGPL-3.0 code on GitHub (commercial license available)",

  "finalCta.title": "Answer every call. Chase every lead.",
  "finalCta.sub": "WorkflowAuth picks up the after-hours call, the lunch-break inquiry, and the lead that almost slipped away — then calls back to follow up. Your team stays on the work; the schedule fills itself.",

  "footer.tag": "The 24/7 AI voice agent that answers every call and chases every lead.",
  "footer.product": "Product",
  "footer.resources": "Resources",
  "footer.legal": "Legal",
  "footer.faq": "FAQ",
  "footer.privacy": "Privacy",
  "footer.terms": "Terms",
  "footer.builtBy": "Built by",
  "footer.bio": "AI build-along videos for developers shipping real agents. Hire me to deploy WorkflowAuth for your business.",
  "footer.copyright": "All rights reserved.",
  "footer.bottomTail": "with care for teams that live on the phone.",

  "lang.label": "Language",

  // ───────── Pricing ─────────
  "pricing.eyebrow": "Simple pricing",
  "pricing.title": "One plan. Everything included.",
  "pricing.sub": "Inbound answering and outbound calling — speed-to-lead, follow-ups, reactivation, and reminders — in a single price.",
  "pricing.planName": "WorkflowAuth",
  "pricing.price": "$70",
  "pricing.period": "/month",
  "pricing.note": "Self-host the open-source code for free, or let us run it for you.",
  "pricing.f1": "24/7 inbound call answering",
  "pricing.f2": "Outbound speed-to-lead, follow-ups & reactivation",
  "pricing.f3": "Appointment reminder calls",
  "pricing.f4": "Configurable lead capture + lead scoring",
  "pricing.f5": "Human transfer rules + post-call digest",
  "pricing.f6": "Your voice, your CRM, your hours",
  "pricing.cta": "Get started",
  "pricing.ctaSecondary": "Book a demo",

  // ───────── ROI / revenue calculator ─────────
  "roi.eyebrow": "Revenue calculator",
  "roi.title": "See what missed calls are costing you.",
  "roi.sub": "Estimate the revenue WorkflowAuth recovers by answering and calling back the leads you miss today.",
  "roi.callsLabel": "Missed calls per month",
  "roi.valueLabel": "Average job value",
  "roi.resultLabel": "Estimated monthly revenue recovered",
  "roi.foot": "Assumes WorkflowAuth books about 1 in 3 of the calls you currently miss — answered live or called back within seconds.",

  // ───────── Founder ─────────
  "founder.name": "Promise Sunday",
  "founder.role": "Founder, WorkflowAuth",
  "founder.note": "I build WorkflowAuth in the open. Want it running for your business? Let's talk.",

  // ───────── Live demo (Mary) ─────────
  "demo.eyebrow": "Live demo",
  "demo.title": "Hear Mary take a call.",
  "demo.sub": "Tap to call and watch the agent capture, score, and book a lead in real time. This is a simulated preview — your real agent runs on your own script, voice, and data.",

  // ───────── Services strip ─────────
  "services.eyebrow": "What it handles",
  "services.title": "One agent. Every call task.",
  "services.sub": "From first ring to follow-up — here's what the agent does across inbound and outbound calls.",

  // ───────── New (post-audit) keys ─────────
  "btn.contact": "Contact",
  "btn.signIn.long": "Sign in",
  "nav.contact": "Contact",
  "menu.open": "Open menu",
  "menu.close": "Close menu",
  "topbar.starGh": "Star on GitHub",

  "hero.platformPill": "AI voice agent · inbound + outbound",
  "hero.secondary": "or book a 15-min demo",
  "hero.tradesPrefix": "For",

  "finalCta.selfHost": "Prefer to self-host? Clone on GitHub",

  // FeatureExplorer
  "fexp.f1.name": "AI Phone Receptionist",
  "fexp.f1.body": "Picks up every inbound call, captures your fields, scores the lead, and books the slot — 24/7.",
  "fexp.f2.name": "Outbound calling",
  "fexp.f2.body": "Speed-to-lead callbacks, follow-ups, reactivation, and reminders — automatic or one-tap.",
  "fexp.f3.name": "AI Chat Assistant",
  "fexp.f3.body": "Same brain on your website, SMS, and WhatsApp. Same brand voice.",
  "fexp.f4.name": "Configurable capture",
  "fexp.f4.body": "Choose the questions and fields. Every lead comes back scored and ranked.",
  "fexp.f5.name": "AI Knowledge Base",
  "fexp.f5.body": "Policies, FAQs, price list — the assistant answers straight from your docs.",
  "fexp.f6.name": "Transfer + digest",
  "fexp.f6.body": "Warm-transfer high-value calls, and get a transcript, summary, and score after each one.",

  // FeatureExplorer demos
  "demo.chat.role": "WorkflowAuth AI · WhatsApp",
  "demo.chat.in1": "Hi, do you have any openings today? I need someone to take a look.",
  "demo.chat.out1": "Yes — I have a slot at 4:20 PM today. Can I grab your name and number to confirm?",
  "demo.chat.in2": "Sure, it's Sam — this number works.",
  "demo.chat.out2": "Booked for 4:20 PM, Sam. I've texted the confirmation and details so you're all set.",
  "demo.chat.pillBooked": "Booked · 4:20 PM",
  "demo.chat.pillEta": "Confirmation sent",
  "demo.crm.title": "Your CRM · Auto-sync",
  "demo.crm.role": "Lead pushed in 2.1s",
  "demo.crm.contact": "Contact",
  "demo.crm.contactVal": "Demo Customer 001 · +1 (000) 123-4567",
  "demo.crm.source": "Source",
  "demo.crm.sourceVal": "Inbound Call · Mary",
  "demo.crm.trade": "Type",
  "demo.crm.tradeVal": "New inquiry",
  "demo.crm.value": "Estimated value",
  "demo.crm.valueVal": "$12,300",
  "demo.crm.temp": "Lead score",
  "demo.crm.tempVal": "92 · Hot",
  "demo.crm.owner": "Next step",
  "demo.crm.ownerVal": "Auto follow-up scheduled",
  "demo.crm.pillCreated": "Lead Created",
  "demo.crm.pillStage": "Stage: Qualified",
  "demo.quote.title": "Outbound Queue",
  "demo.quote.role": "Next callback in 00:42",
  "demo.quote.row1": "Speed-to-lead · new inbound (Jordan)",
  "demo.quote.row2": "Follow-up · quote sent Tuesday",
  "demo.quote.row3": "Reactivation · lead cold 38 days",
  "demo.quote.totalLabel": "Queued for today",
  "demo.quote.pill": "3 callbacks · auto-dialing",
  "demo.kb.title": "Knowledge Base",
  "demo.kb.role": "Answer pulled from your docs",
  "demo.kb.in1": "What's your service area, and are you open on weekends?",
  "demo.kb.out1": "We cover the whole metro and we're open Saturdays 9 to 2. Would you like me to book a time?",
  "demo.kb.in2": "Yes, Saturday morning if you have it.",
  "demo.kb.out2": "Booked for Saturday 9 AM. You'll get an SMS confirmation shortly.",
  "demo.kb.pill": "Cited your policies doc · §4.3",
  "demo.analytics.title": "This week",
  "demo.analytics.role": "Sept 23 – 29",
  "demo.analytics.s1n": "92%",
  "demo.analytics.s1l": "Calls answered < 2 rings",
  "demo.analytics.s2n": "146",
  "demo.analytics.s2l": "Leads called back",
  "demo.analytics.s3n": "31",
  "demo.analytics.s3l": "Cold leads reactivated",
  "demo.analytics.s4n": "41s",
  "demo.analytics.s4l": "Avg speed-to-lead",
  "demo.analytics.pill": "+12% vs last week",

  // Mock dashboard
  "mock.crumb": "Overview",
  "mock.search": "Search…",
  "mock.kpi.leads": "Total Leads",
  "mock.kpi.leadsDelta": "+12% vs last 30d",
  "mock.kpi.quotes": "Callbacks Placed",
  "mock.kpi.quotesDelta": "+8% connect rate",
  "mock.kpi.bookings": "Appointments Booked",
  "mock.kpi.bookingsDelta": "+4 this week",
  "mock.section.title": "Recent Interactions",
  "mock.live": "Live",
  "mock.filter": "Filter",
  "mock.col.contact": "Contact",
  "mock.col.assistant": "Assistant",
  "mock.col.activity": "Activity",
  "mock.col.action": "Action",
  "mock.foot": "Showing 6 of 198",
  "mock.openReal": "Open the real dashboard",
  "mock.justNow": "Just now",
  "mock.secAgo": "{n}s ago",
  "mock.minAgo": "{n}m ago",
  "mock.hourAgo": "{n}h ago",
  "mock.channel.phone": "phone",
  "mock.channel.sms": "SMS",
  "mock.channel.whatsapp": "WhatsApp",
  "mock.channel.chat": "web chat",
  "mock.channel.email": "email",
  "mock.business": "Demo Business Inc.",
  "mock.msg1": "Confirmed — Tuesday morning works for the appointment.",
  "mock.msg2": "Calling back about your inquiry from earlier today.",
  "mock.msg3": "Can someone reach me this Saturday morning?",
  "mock.msg4": "Following up on the estimate we sent last week.",
  "mock.msg5": "New lead — wanted details on your services and pricing.",
  "mock.msg6": "Checking on my order status. Order #5521.",
  "mock.msg7": "Reactivation call — happy to pick things back up.",
  "mock.msg8": "Reminder: appointment tomorrow at 9 AM.",

  "phoneWidget.incoming": "Incoming Call",
  "phoneWidget.frontDesk": "Mary · front desk",
  "phoneWidget.decline": "Decline",
  "phoneWidget.accept": "Accept",
  "phoneWidget.answering": "Mary is answering…",
  "phoneWidget.t1": "Hi, I'd like to book an appointment and ask a couple of questions.",
  "phoneWidget.t2": "Of course — I can help with both. Can I start with your name and number?",
  "phoneWidget.t3": "It's Alex, and this number is best.",
  "phoneWidget.t4": "Thanks, Alex. Saturday at 9 AM is open — shall I book it in?",

  "pill.dealWon": "Lead Won",
  "pill.quoteSent": "Callback Placed",
  "pill.booked": "Booked",
  "pill.subsidy": "Reactivated",
  "pill.qualifying": "Qualifying",

  // LiveTicker
  "ticker.callsToday": "calls handled today",
  "ticker.i1": "Lead won · booked appointment",
  "ticker.i2": "Speed-to-lead callback placed in 38s",
  "ticker.i3": "New lead qualified via SMS · scored 88",
  "ticker.i4": "Saturday 9 AM booked · new appointment",
  "ticker.i5": "Cold lead reactivated after 41 days",
  "ticker.i6": "Mary answered call · 02:14 duration",
  "ticker.i7": "Follow-up call connected · quote revived",
  "ticker.i8": "Appointment reminder call · confirmed",
  "ticker.i9": "After-hours call answered · lead captured",
  "ticker.i10": "Tuesday 9:30 AM booked on the calendar",
  "ticker.i11": "Inbound lead scored 95 · routed to owner",
  "ticker.i12": "Lead won · re-engaged from last quarter",
  "ticker.i13": "Missed call → callback → booked in 2 min",
  "ticker.i14": "Warm transfer to on-call human · high value",
  "ticker.i15": "After-hours call qualified · follow-up queued",
  "ticker.i16": "Friday 11 AM appointment booked",
  "ticker.i17": "WhatsApp lead → callback in 41 seconds",
  "ticker.i18": "Reactivation campaign · 9 leads re-engaged",

  // StatsBand
  "stats.eyebrow.short": "Why teams switch",
  "stats.title.short": "Every missed call is a job your competitor books.",
  "stats.body.short": "WorkflowAuth answers every inbound, and calls back the leads you miss — speed-to-lead, follow-ups, and reactivation, all on autopilot. It never sleeps and never takes a break.",
  "stats.li1.short": "Inbound calls answered while your team is offline",
  "stats.li2.short": "New leads called back within seconds, automatically",
  "stats.li3.short": "Cold and lost leads reactivated without lifting a finger",
  "stats.cardA.label": "of after-hours calls picked up — the ones your voicemail used to lose.",
  "stats.cardB.label": "average speed-to-lead: new leads get a callback within the minute.",
  "stats.cardC.label": "average time-to-first-response across phone, SMS, and chat.",

  // Mobile apps band
  "apps.eyebrow": "Now on iPhone & Android",
  "apps.title": "WorkflowAuth in your pocket.",
  "apps.body": "The WorkflowAuth mobile apps put every lead, call, and callback on your home screen. Tap a push, open the conversation, place a call. Built native — SwiftUI on iOS, Jetpack Compose on Android — against the same self-hostable backend.",
  "apps.f1.title": "Leads in your pocket",
  "apps.f1.body": "Qualified, scored leads sync to your phone the second they land — name, intent, score, value.",
  "apps.f2.title": "Push the moment a lead lands",
  "apps.f2.body": "Tap a notification to jump straight into the customer's conversation. No noise, just signal.",
  "apps.f3.title": "Manage outbound on the go",
  "apps.f3.body": "See the callback queue, place a call now, or reschedule a follow-up from anywhere.",
  "apps.f4.title": "Call transcripts on the go",
  "apps.f4.body": "Skim what the assistant and the caller said, grouped by day. Catch up on yesterday's calls in two minutes.",
  "apps.appleTop": "Coming soon to the",
  "apps.appleBottom": "App Store",
  "apps.googleTop": "COMING SOON ON",
  "apps.googleBottom": "Google Play",
  "apps.note": "Self-hosting? Both apps point to your own backend via a single \"API URL\" setting in the app. One binary on the stores, your data on your server.",

  // ChatWidget
  "chat.intro": "Hi! I'm Mary from WorkflowAuth. Want to book a time, ask a question, or have us call you back?",
  "chat.handoffIntro": "Connecting you to a human teammate — they'll see this conversation and reply here.",
  "chat.teaser.title": "WorkflowAuth · Mary",
  "chat.teaser.body": "Hi! Want to book a time or have us call you back? Ask me anything.",
  "chat.dismissTeaser": "Dismiss assistant teaser",
  "chat.openLabel": "Open assistant chat",
  "chat.closeLabel": "Close chat",
  "chat.role": "WorkflowAuth AI · replies in seconds",
  "chat.placeholder": "Type a message…",
  "chat.send": "Send",
  "chat.quick.quote": "Book a time",
  "chat.quick.book": "Request a callback",
  "chat.quick.subsidy": "Ask a question",
  "chat.error.send": "Couldn't deliver that message — please try again in a moment.",
  "chat.error.closed": "This conversation is closed. Start a new one to keep talking.",
  "chat.script.q1": "Can you call me back about my inquiry?",
  "chat.script.a1a": "Absolutely — what's the best number and a good time to reach you?",
  "chat.script.a1b": "We typically call new leads back within a minute.",
  "chat.script.q2": "Can someone come Saturday morning?",
  "chat.script.a2a": "I have Saturday at 9 AM open.",
  "chat.script.a2b": "Want me to lock that in and text you the confirmation?",
  "chat.script.q3": "What are your hours and service area?",
  "chat.script.a3a": "We're open Saturdays 9 to 2 and cover the whole metro.",
  "chat.script.a3b": "I can book you a time or have someone call you right back.",
  "chat.quick.human": "Talk to a human",
  "chat.live.support": "WorkflowAuth Support",
  "chat.live.connected": "Connected to a human · live",
  "chat.live.connecting": "Connecting…",
  "chat.live.title": "Live chat",
  "chat.live.placeholder": "Message a human…",
  "chat.live.end": "End live chat",
  "chat.live.startNew": "Start a new chat",
  "chat.live.closedBanner": "This conversation is closed. Start a new chat to send another message.",
  "chat.live.unreachable": "We couldn't reach a human agent right now. Please try again shortly.",
  "chat.live.welcomeBack": "Welcome back — picking up where you left off.",
  "chat.live.backToMary": "You're back with Mary. Want to ask something else?",
  "chat.intake.title": "Before we connect you",
  "chat.intake.sub": "So our team knows who they're talking to.",
  "chat.intake.name": "Name",
  "chat.intake.namePh": "Jane Doe",
  "chat.intake.email": "Email",
  "chat.intake.emailPh": "jane@example.com",
  "chat.intake.cancel": "Cancel",
  "chat.intake.submit": "Start chat",
  "chat.intake.submitting": "Connecting…",
  "chat.intake.errName": "Please enter your name.",
  "chat.intake.errEmail": "Please enter a valid email.",

  // Mary demo launcher + modal
  "maryLaunch.cta": "Hear Mary pick up",
  "maryModal.eyebrow": "Live demo · simulated call",
  "maryModal.title": "Watch Mary take an after-hours call.",
  "maryModal.dialing": "Customer dialing in…",
  "maryModal.statusRinging": "Incoming call · ringing…",
  "maryModal.statusConnected": "Connected",
  "maryModal.statusEnded": "Call ended · summary saved to CRM",
  "maryModal.summaryTitle": "What just happened",
  "maryModal.summary1": "Lead captured and scored · 92",
  "maryModal.summary2": "Appointment booked · Tomorrow 7:45 AM",
  "maryModal.summary3": "Customer texted confirmation + details",
  "maryModal.summary4": "Follow-up call auto-scheduled",
  "maryModal.foot": "This is a scripted preview. The real Mary runs on your business's own questions, voice, and CRM.",
  "maryModal.bookReal": "Book a real demo",
  "maryModal.openSim": "Open the full simulator",
  "maryModal.talkLive": "Talk to Mary live",
  "maryModal.backToDemo": "Back to demo",

  // Live voice call (Vapi web)
  "mary.live.context": "This live demo is set up as a home-service receptionist — HVAC, plumbing, solar, roofing, electrical. Call Mary like a customer would. (We deploy her for other industries too.)",
  "mary.live.ready": "Ready when you are — tap to talk to Mary.",
  "mary.live.start": "Start talking",
  "mary.live.again": "Talk again",
  "mary.live.connecting": "Ringing Mary…",
  "mary.live.micHint": "Your browser will ask for microphone access.",
  "mary.live.live": "Live with Mary",
  "mary.live.ended": "Call ended. Thanks for chatting with Mary.",
  "mary.live.error": "Couldn't start the call. Please try again.",
  "mary.live.micError": "Microphone blocked. Allow mic access in your browser, then try again.",
  "mary.live.timeout": "Couldn't connect — check your internet connection and try again.",
  "mary.live.sayHi": "Say hello — Mary's listening.",
  "mary.live.you": "You",
  "mary.live.mute": "Mute",
  "mary.live.unmute": "Unmute",
  "mary.live.hangup": "End call",
  "mary.live.close": "Close",
  "mary.live.consent": "You're talking to an AI receptionist. Calls may be recorded to improve quality. Max 5 minutes.",
  "mary.live.soonTitle": "Live voice is almost ready",
  "mary.live.soonBody": "Real-time voice with Mary isn't switched on for this site yet. Book a call and you'll hear her on a real line.",
  "maryModal.line1": "Hi, this is the Mary at WorkflowAuth — how can I help tonight?",
  "maryModal.line2": "Hi, I wanted to book an appointment but it's after hours.",
  "maryModal.line3": "No problem at all — I can book that for you right now. May I have your name?",
  "maryModal.line4": "Sure, it's Taylor.",
  "maryModal.line5": "Thanks, Taylor. I can get you in by 7:45 AM tomorrow. Shall I book it and text you the confirmation?",

  // /docs
  "docs.eyebrow": "Built in public · AGPL-3.0 · Self-hostable",
  "docs.title": "Self-host WorkflowAuth.",
  "docs.sub": "Same dashboard, same AI pipeline, same code we ship in the YouTube build-alongs — yours under AGPL-3.0. Three commands and you're running the full stack locally.",
  "docs.tocStarted": "Get started",
  "docs.tocConcepts": "Concepts",
  "docs.tocIntegrations": "Integrations",
  "docs.tocProject": "Project",
  "docs.toc.quickstart": "Quick start",
  "docs.toc.architecture": "Architecture",
  "docs.toc.stack": "What's in the repo",
  "docs.toc.pipeline": "The agent loop",
  "docs.toc.voice": "Wiring real voice",
  "docs.toc.demoData": "Seed demo data",
  "docs.toc.roadmap": "Roadmap",
  "docs.toc.license": "License",
  "docs.toc.starGh": "★ Star on GitHub",
  "docs.toc.buildAlong": "▶ Build along on YouTube",
  "docs.h.quickstart": "Quick start",
  "docs.h.architecture": "Architecture overview",
  "docs.h.stack": "What's in the repo",
  "docs.h.pipeline": "The agent loop",
  "docs.h.voice": "Wiring real voice",
  "docs.h.demoData": "Seed demo data",
  "docs.h.roadmap": "Roadmap",
  "docs.h.license": "License",
  "docs.archP": "Three Docker services, two AI providers, one Postgres. The frontend renders server components against a Django REST API; voice runs through Vapi's custom-LLM mode so the assistant keeps a real agent loop server-side.",
  "docs.arch.caller": "Caller",
  "docs.arch.callerSub": "Phone · SMS · WhatsApp · web chat · email",
  "docs.arch.vapi": "Vapi / Twilio",
  "docs.arch.vapiSub": "Voice handling, transcript per turn",
  "docs.arch.django": "Django + Mary",
  "docs.arch.djangoSub": "Claude tool loop, persists to Postgres",
  "docs.arch.next": "Next.js dashboard",
  "docs.arch.nextSub": "Server components, live KPIs, outbound queue",
  "docs.stackP": "Every box below is wired up in code. Click the path to jump straight to the file on GitHub.",
  "docs.pipelineP": "Six stages, each one a single function, webhook, or tool dispatch in the codebase. Trace it with your IDE in five minutes.",
  "docs.voiceP1": "Drop your Vapi key in .env and point the assistant webhook at a tunnel of your local backend (or your deployed URL):",
  "docs.voiceP2.pre": "The custom-LLM completions endpoint lives at",
  "docs.voiceP2.post": " — Vapi POSTs the running transcript on every turn and the agent loop returns the next utterance.",
  "docs.demoP": "One management command. Wipes the existing demo set and inserts believable leads, calls, and callbacks — enough to see every dashboard view come alive.",
  "docs.roadmapP": "Pull requests welcome. Each line below is a real GitHub issue.",
  "docs.licenseP.pre": "The reference implementation is published under the ",
  "docs.licenseP.mid": ". A separate commercial license is available for white-labeling, reselling, or embedding WorkflowAuth in closed-source products — email ",
  "docs.licenseP.post": ".",
  "docs.next.vapi": "Wire up Vapi",
  "docs.next.vapiSub": "Drop your key in .env and point a webhook.",
  "docs.next.seed": "Seed demo data",
  "docs.next.seedSub": "One command — the dashboard fills with believable rows.",
  "docs.next.deploy": "Deploy to a VPS",
  "docs.next.deploySub": "Docker Compose + Caddy auto-HTTPS in DEPLOY.md.",
  "docs.cloneCta": "★ Clone on GitHub",
  "docs.signinCta": "Sign in to dashboard",
  "docs.roadmap.shipped": "Shipped",
  "docs.roadmap.wip": "In progress",
  "docs.roadmap.todo": "Open issues",

  // FAQ
  "faq.heroEyebrow": "Frequently asked questions",
  "faq.heroT1": "Honest answers.",
  "faq.heroT2": "No marketing fluff.",
  "faq.heroSub": "Setup, pricing, integrations, security — the things teams actually ask before signing up.",
  "faq.cat.all": "All",
  "faq.cat.setup": "Setup",
  "faq.cat.product": "Product",
  "faq.cat.pricing": "Pricing",
  "faq.cat.security": "Security",
  "faq.cat.oss": "Open source",
  "faq.finalT": "Still have a question?",
  "faq.finalSub": "Book a 15-minute call and ask directly.",

  // Contact page
  "contact.heroEyebrow": "Get in touch",
  "contact.heroT1": "Talk to a human.",
  "contact.heroT2": "Or send a ticket.",
  "contact.heroSub": "Demo bookings, self-host setup, partnership questions, or just feedback — pick the lane that fits and we'll get back to you.",
  "contact.ch1.title": "Book a 15-min call",
  "contact.ch1.body": "Walk through your setup, pricing, and rollout with Promise (founder).",
  "contact.ch1.cta": "Pick a time",
  "contact.book.eyebrow": "Book a call",
  "contact.book.title": "Grab a 15-minute slot.",
  "contact.book.sub": "Pick a time that works and we'll walk through your AI front desk — no pressure, no pitch deck.",
  "contact.book.cta": "Pick a time",
  "contact.ch2.title": "Email support",
  "contact.ch2.body": "Best for billing, deployments, or anything you'd rather not type into a form.",
  "contact.ch3.title": "Open an issue",
  "contact.ch3.body": "Bugs, feature requests, and architecture questions live on GitHub.",
  "contact.creatorRole": "Builds WorkflowAuth live · @workflowauth",
  "contact.creatorBio": "AI build-along videos for developers shipping real agents. Hire me to deploy WorkflowAuth for your business.",
  "contact.cardTitle": "Send a ticket",
  "contact.cardSub": "Average reply < 1 hour during business days. Tickets are saved to the dashboard and emailed to our team — we respond from promise@workflowauth.com.",
  "contact.f.name": "Your name",
  "contact.f.email": "Email",
  "contact.f.subject": "Subject",
  "contact.f.subjectPh": "What's this about?",
  "contact.f.body": "Message",
  "contact.f.bodyPh": "Describe your question or issue. The more detail, the faster we can help.",
  "contact.f.send": "Send ticket",
  "contact.f.sending": "Sending…",
  "contact.f.hint": "Or use the chat bubble for live help.",
  "contact.success.title": "Ticket received",
  "contact.success.again": "Submit another ticket",
  "contact.error.required": "Please fill in your name, email, and message.",
  "contact.error.email": "Please enter a valid email.",
  "contact.error.fallback": "Could not submit ticket. Please try again.",

  // Login
  "login.title": "Welcome back",
  "login.sub.pre": "Sign in to your WorkflowAuth dashboard. Don't have an account? ",
  "login.sub.cta": "Book a demo",
  "login.email": "Email or username",
  "login.emailPh": "you@company.com",
  "login.password": "Password",
  "login.show": "Show",
  "login.hide": "Hide",
  "login.submit": "Sign in",
  "login.submitting": "Signing in…",
  "login.foot.pre": "Trouble signing in? Email ",
  "login.back": "← Back to home",
  "login.error.fallback": "Could not sign you in. Check your credentials.",
  "login.error.network": "Network error. Try again.",

  // MissedCallStory scene captions
  "story.scene.incoming": "Calling · 11:47 PM",
  "story.scene.calling": "calling",
  "story.scene.onLine": "on the line",
  "story.scene.transcript": "\"Hi, this is the Mary at WorkflowAuth. I can help you tonight — what do you need?\"",
  "story.scene.calHead": "This week",
  "story.scene.calNew": "3 new bookings overnight",
  "story.scene.cal.survey": "New appointment",
  "story.scene.cal.tagNew": "Mary · new",
  "story.scene.cal.hvac": "Follow-up call",
  "story.scene.cal.roof": "Reactivated lead",

  // ───────── Landing rebuild (ignitvio-style flow) ─────────
  // Nav
  "nav.deploy": "What we deploy",
  "nav.why": "Why us",
  "nav.about": "About",

  // Hero (revenue-loss framing)
  "hero2.pill": "AI front desk · inbound + outbound",
  "hero2.title1": "The AI front desk that never misses a lead.",
  "hero2.title2": "Day, night, and after hours.",
  "hero2.sub": "Stop losing revenue to missed calls. WorkflowAuth answers every call your team can't get to, qualifies the lead, books the job, and calls back the ones that slip away — so revenue stops leaking into voicemail at 6:01 PM.",
  "hero2.primary": "See what I'm losing",
  "hero2.secondary": "Calculate my revenue loss",
  "hero2.tradesPrefix": "Built for",
  "hero2.tradesList": "HVAC · Plumbing · Roofing · Dental · Medspa · Real estate",

  // Problem stats
  "problem.eyebrow": "The leak",
  "problem.title": "Your phone's ringing. Nobody's answering.",
  "problem.sub": "Every call that hits voicemail is a customer dialing your competitor next. Here's what it quietly costs you.",
  "problem.s1.num": "62%",
  "problem.s1.label": "of callers won't leave a voicemail — they hang up and call the next business on the list.",
  "problem.s2.num": "10×",
  "problem.s2.label": "drop in conversion when you don't answer a new lead within the first five minutes.",
  "problem.s3.num": "40%",
  "problem.s3.label": "of leads come in after hours, on weekends, or while you're already on another job.",
  "problem.without.title": "Without WorkflowAuth",
  "problem.without.1": "Call rings out → voicemail",
  "problem.without.2": "Lead calls a competitor",
  "problem.without.3": "You find out tomorrow — too late",
  "problem.without.4": "Revenue leaks into voicemail",
  "problem.with.title": "With WorkflowAuth",
  "problem.with.1": "Mary answers on the second ring",
  "problem.with.2": "Lead qualified and scored live",
  "problem.with.3": "Job booked, SMS confirmation sent",
  "problem.with.4": "Clean lead in your CRM by morning",

  // Revenue-loss calculator section head (inputs reuse roi.* labels)
  "cost.eyebrow": "Revenue calculator",
  "cost.title": "Where your revenue disappears.",
  "cost.sub": "Plug in your numbers. This is the booked work WorkflowAuth recovers from the calls you miss today.",

  // How it works
  "how.eyebrow": "How it works",
  "how.title": "Three steps. Zero complexity.",
  "how.sub": "You stay on the tools. We handle the build, the deploy, and the calls.",
  "how.s1.n": "01",
  "how.s1.title": "Free revenue audit",
  "how.s1.body": "We map where leads are leaking — missed calls, slow callbacks, dropped follow-ups — and what it's costing you every month.",
  "how.s2.n": "02",
  "how.s2.title": "We build & deploy Mary",
  "how.s2.body": "Your script, your voice, your hours, your CRM. We wire up inbound answering and outbound callbacks, then test it end to end.",
  "how.s3.n": "03",
  "how.s3.title": "You get more booked jobs",
  "how.s3.body": "Mary answers every call and chases every lead, day and night. You wake up to a fuller calendar and a clean pipeline.",

  // What we deploy
  "deploy.eyebrow": "What we deploy",
  "deploy.title": "Systems that work while you sleep.",
  "deploy.sub": "A complete front desk — inbound and outbound — running on autopilot.",
  "deploy.d1.title": "Never miss a call",
  "deploy.d1.body": "An AI receptionist answers every inbound within two rings, qualifies the caller, and books the job in a voice you choose.",
  "deploy.d2.title": "Instant lead follow-up",
  "deploy.d2.body": "New lead comes in? Mary calls or texts back within seconds — speed-to-lead that wins the deal before a competitor picks up.",
  "deploy.d3.title": "24/7 booking",
  "deploy.d3.body": "Appointments booked around the clock, straight into your calendar, with an SMS confirmation that cuts no-shows.",
  "deploy.d4.title": "Reactivation & reminders",
  "deploy.d4.body": "Cold leads re-engaged, quotes that went quiet revived, and appointment reminders placed automatically.",

  // Industries (home-service trades up front + other verticals we serve)
  "ind.eyebrow": "Who it's for",
  "ind.title": "Built for local service businesses.",
  "ind.sub": "From home-service trades to clinics and real estate — if your business runs on the phone, Mary fits right in.",
  "ind.hvac.name": "HVAC",
  "ind.hvac.body": "After-hours service calls, speed-to-lead callbacks, and job scheduling — captured before the competitor answers.",
  "ind.plumbing.name": "Plumbing",
  "ind.plumbing.body": "Emergency calls triaged, drips and clogs booked, and quotes followed up — day, night, and weekends.",
  "ind.solar.name": "Solar installation",
  "ind.solar.body": "New inquiries qualified, site assessments scheduled, and warm leads called back in seconds.",
  "ind.roofing.name": "Roofing",
  "ind.roofing.body": "Storm-damage and inspection calls answered live, estimates booked, and quiet quotes revived.",
  "ind.electrical.name": "Electrical",
  "ind.electrical.body": "Service requests captured, panel and rewire jobs scheduled, and callbacks placed automatically.",
  "ind.also.label": "Also serving",
  "ind.also.1": "Dental clinics",
  "ind.also.2": "Medspas",
  "ind.also.3": "Real estate",
  "ind.note": "Another industry? WorkflowAuth adapts to any business that books work over the phone. ",

  // Why us comparison table
  "why.eyebrow": "Why WorkflowAuth",
  "why.title": "The math is simple.",
  "why.sub": "What you get, versus the alternatives.",
  "why.col.us": "WorkflowAuth",
  "why.col.vm": "Voicemail",
  "why.col.recept": "Receptionist hire",
  "why.col.bot": "Generic chatbot",
  "why.r1.l": "Answers every call 24/7",
  "why.r2.l": "Books the appointment",
  "why.r3.l": "Qualifies & scores the lead",
  "why.r4.l": "Calls leads back automatically",
  "why.r5.l": "Monthly cost",
  "why.r5.us": "$70",
  "why.r5.vm": "$0",
  "why.r5.recept": "$3,000+",
  "why.r5.bot": "$50–500",
  "why.r6.l": "Live in",
  "why.r6.us": "~3 days",
  "why.r6.vm": "—",
  "why.r6.recept": "Weeks",
  "why.r6.bot": "Days",
  "why.r7.l": "Never sick, never quits",

  // About / founder
  "about.eyebrow": "About",
  "about.title": "Enterprise expertise. Local focus.",
  "about.body": "I spent two years helping home-service and healthcare companies automate their operations. Now that same operational expertise goes to the local businesses that build our communities — HVAC, plumbing, roofing, and electrical, plus dental clinics, medspas, and real estate. I bring enterprise-grade automation to local service businesses, without the enterprise complexity or the price tag.",
  "about.name": "Promise Sunday",
  "about.role": "Founder, WorkflowAuth",

  // FAQ on landing
  "faq2.eyebrow": "FAQ",
  "faq2.title": "Questions, answered straight.",
  "faq2.sub": "The things teams actually ask before they switch.",
  "faq2.more": "See all questions →",

  // Final CTA (revenue-audit framing)
  "finalCta2.title": "Book a free 15-minute revenue audit.",
  "finalCta2.sub": "We'll show you exactly where leads are leaking — and what WorkflowAuth recovers. No pressure, no pitch deck.",
};

export function tEn(key: string): string {
  return en[key] ?? key;
}
