export type Dict = Record<string, string>;

export const en: Dict = {
  "nav.features": "Features",
  "nav.how": "How it works",
  "nav.impact": "Impact",
  "nav.industries": "Industries",
  "nav.docs": "Docs",
  "btn.signIn": "Sign in",
  "btn.bookDemo": "Book a demo",
  "btn.explore": "Explore",
  "btn.tellUs": "Tell us about yours",
  "topbar.builtBy": "by",

  "hero.meetStrong": "Hi, I'm Mary.",
  "hero.meetTail": " I'm on the phones tonight — go to bed.",
  "hero.tradesLabel": "Built for home services —",
  "hero.tradesList": "HVAC · Plumbing · Solar · Roofing · +5 more trades",
  "hero.title1": "It's 11:47pm. Your phone is ringing.",
  "hero.title2": "Don't worry about it.",
  "hero.sub": "Mary answers, qualifies, quotes, and books — so your crew sleeps and your calendar fills itself.",
  "story.eyebrow": "What it feels like",
  "story.title1": "One missed call,",
  "story.title2": "turned into a booked job.",
  "story.sub": "Scroll through a single night, the way Mary actually handles it.",
  "story.s1.beat": "It's late. The phone rings.",
  "story.s1.body": "11:47pm. Your team is asleep. The competitor down the road is too. The lead has 30 seconds of patience.",
  "story.s2.beat": "Mary picks up.",
  "story.s2.body": "She greets the caller in your business's voice, asks the right qualifying questions, and learns it's a 5-window job in the living room.",
  "story.s3.beat": "Quote. Confirmed.",
  "story.s3.body": "Mary walks the caller through the scope, drafts a $3,540 estimate from your price book, and offers a Tuesday 9:30 AM survey slot — all before they go to bed.",
  "story.s4.beat": "You wake up booked.",
  "story.s4.body": "Morning coffee. One survey on the calendar, one estimate already sent, one deposit waiting. You haven't touched the phone.",
  "story.s4.foot": "All overnight. No one was awake.",

  "hero.oss": "Open-source · AGPL-3.0",
  "hero.star": "★ Star on GitHub",
  "hero.selfHost": "Self-host or done-for-you setup",

  "features.eyebrow": "Features",
  "features.title": "Configure once. Captures every lead.",
  "features.sub": "Set your business hours, pricing rules, and service area. Workflow Auth adapts to your trade — from emergency plumbing at 2 AM to a $25k solar quote at noon.",
  "features.f1.name": "AI Phone Receptionist",
  "features.f1.body": "Never miss a call again. Workflow Auth picks up every inbound within two rings, qualifies the lead in real time, and books the slot directly into your team's calendar — in a voice you choose, with the script your business runs on.",
  "features.f2.name": "AI Chat Assistant",
  "features.f2.body": "Web chat, SMS, and WhatsApp — same Mary, same memory of the customer. Replies in seconds, hands off to a human only when she should.",
  "features.f3.name": "CRM Integration",
  "features.f3.body": "Every call, text, and quote pushes into your CRM as a clean record — HubSpot, Pipedrive, Jobber, ServiceTitan, or your own Postgres.",
  "features.f4.name": "Smart Quoting",
  "features.f4.body": "Mary drafts line items live on the call from your price book, applies your tax + margin rules, and sends a Stripe-ready estimate while the customer is still on the line.",
  "features.f5.name": "AI Knowledge Base",
  "features.f5.body": "Drop in your warranty doc, service catalog, and FAQ. Mary quotes your real terms — never invents a price or a promise you don't make.",
  "features.f6.name": "Data Analytics",
  "features.f6.body": "Live dashboards on call volume, lead quality, conversion, and revenue per channel — so you can prove the night shift is paying for itself.",

  "stats.eyebrow": "Why teams switch",
  "stats.title": "Every missed call is a job your competitor books.",
  "stats.body": "Workflow Auth picks up every inbound across every channel, qualifies it on the spot, and hands your crew a deal-ready conversation. Mary never sleeps and never takes a smoke break.",
  "stats.li1": "Calls answered while you're on a roof at 3 AM",
  "stats.li2": "Quotes drafted live on the call before you finish your coffee",
  "stats.li3": "Every interaction synced to HubSpot, Pipedrive, or your CRM",
  "stats.card1.num": "3 AM",
  "stats.card1.label": "The burst-pipe call your competitor missed last Tuesday. Mary picked it up.",
  "stats.card2.num": "43 sec",
  "stats.card2.label": "Average time from caller hello to a drafted estimate in your dashboard.",
  "stats.card3.num": "$0",
  "stats.card3.label": "Per missed call. Workflow Auth books the ones your inbox loses.",

  "flow.eyebrow": "How it flows",
  "flow.title": "How a job flows through Workflow Auth.",
  "flow.sub": "Five stages, fully automated. The customer never feels the handoffs — they just get a quick answer, a quote, and a booked time slot.",

  "convo.eyebrow": "A real conversation",
  "convo.title": "Mary handles the objection, not just the hello.",
  "convo.sub": "Live SMS thread between Mary and a customer. Lead qualified, quote drafted, deal created, calendar booked — all auto.",
  "convo.head.title": "Inbound Lead Automation",
  "convo.head.sub": "Qualifies the lead, syncs to CRM, drafts an estimate — automatically.",
  "convo.msg1": "I need to replace about 5 windows in my living room. Looking for white PVC.",
  "convo.msg2": "Got it — 5 PVC windows, white. Standard double-glazed, or do you want triple for noise / energy? And what's the rough opening size — about 120×140 cm?",
  "convo.msg3": "Double-glazed is fine, and yes around that size.",
  "convo.msg4Pre": "Perfect — five units, supply and install: ",
  "convo.msg4Mid": " incl. tax. I've texted the breakdown and a Tuesday 9:30 AM survey slot. Tap the link to confirm.",
  "convo.output": "Output Result",
  "convo.estimate": "Estimate #E-291 · sent",
  "convo.deal": "Deal Created · HubSpot",
  "convo.survey": "Survey Booked · Tue 9:30 AM",
  "convo.signed": "— Mary",

  "industries.eyebrow": "Trades",
  "industries.title": "One platform. Every trade.",
  "industries.sub": "Pricing logic, scripts, and dispatch rules come pre-tuned for each trade — and are fully editable. Don't see yours? Workflow Auth configures to any home-service workflow.",
  "industries.note": "Plus: not in this list? Workflow Auth plugs into any workflow your team already runs. ",
  "industries.i1.name": "HVAC & Plumbing",
  "industries.i1.body": "Emergency-call routing 24/7, technician dispatch, maintenance contracts.",
  "industries.i2.name": "Windows & Doors",
  "industries.i2.body": "Measurement scheduling, installation bookings, after-hours quote requests.",
  "industries.i3.name": "Solar & Roofing",
  "industries.i3.body": "Roof-type qualification, rebate matching, site-survey coordination.",
  "industries.i4.name": "Energy Renovation",
  "industries.i4.body": "Insulation audits, subsidy applications, multi-step renovation flows.",
  "industries.i5.name": "Garage & Shutters",
  "industries.i5.body": "Brand + model identification, repair vs replace triage, after-hours calls.",
  "industries.i6.name": "Electrical",
  "industries.i6.body": "Emergency vs scheduled job triage, safety-warning scripts, smart-home upsells.",
  "industries.i7.name": "Landscaping & Pools",
  "industries.i7.body": "Seasonal scheduling, recurring contracts, multi-job estimates.",
  "industries.i8.name": "Cleaning & Restoration",
  "industries.i8.body": "Damage triage, insurance routing, recurring booking, before/after photos.",
  "industries.i9.name": "Pest Control",
  "industries.i9.body": "Symptom triage, recurring contracts, neighbour-coverage upsell, follow-ups.",

  "config.eyebrow": "Configurable end-to-end",
  "config.title": "Your voice. Your pricing. Your CRM. Your hours.",
  "config.body": "Pick from 30+ neural voices in 7 languages. Drop in your price book. Connect HubSpot, Pipedrive, Salesforce, ServiceTitan, or your custom API. Set business hours per channel. Workflow Auth runs on your rules — not the other way around.",
  "config.k1.l": "Voice",
  "config.k1.v": "30+ neural · 7 languages",
  "config.k2.l": "Pricing",
  "config.k2.v": "Your price book · per-trade rules",
  "config.k3.l": "CRM",
  "config.k3.v": "HubSpot · Pipedrive · Salesforce · API",
  "config.k4.l": "Hours",
  "config.k4.v": "Per-channel · per-day · holidays",
  "config.k5.l": "Voice cloning",
  "config.k5.v": "Use your owner's voice (optional)",
  "config.k6.l": "Self-host",
  "config.k6.v": "AGPL-3.0 code on GitHub (commercial license available)",

  "finalCta.title": "Keep the fire on. We'll watch the door.",
  "finalCta.sub": "Mary picks up the 3 AM emergency, the lunch-break callback, and the after-hours estimate request. Your team stays on the tools — the schedule fills itself.",

  "footer.tag": "The 24/7 AI communication hub for home-service teams.",
  "footer.product": "Product",
  "footer.resources": "Resources",
  "footer.legal": "Legal",
  "footer.faq": "FAQ",
  "footer.privacy": "Privacy",
  "footer.terms": "Terms",
  "footer.builtBy": "Built by",
  "footer.bio": "AI build-along videos for developers shipping real agents. Hire me to deploy Workflow Auth for your business.",
  "footer.copyright": "Open-source under AGPL-3.0. Commercial license available.",
  "footer.bottomTail": "with care for home-service teams.",

  "lang.label": "Language",

  // ───────── New (post-audit) keys ─────────
  "btn.contact": "Contact",
  "btn.signIn.long": "Sign in",
  "nav.contact": "Contact",
  "menu.open": "Open menu",
  "menu.close": "Close menu",
  "topbar.starGh": "Star on GitHub",

  "hero.platformPill": "For home-services businesses",
  "hero.secondary": "or book a 30-min demo",
  "hero.tradesPrefix": "For",

  "finalCta.selfHost": "Prefer to self-host? Clone on GitHub",

  // FeatureExplorer
  "fexp.f1.name": "AI Phone Receptionist",
  "fexp.f1.body": "Mary picks up every call, qualifies the lead, and books the slot — 24/7.",
  "fexp.f2.name": "AI Chat Assistant",
  "fexp.f2.body": "Same brain on your website, SMS, and WhatsApp. Same brand voice.",
  "fexp.f3.name": "CRM Integration",
  "fexp.f3.body": "Every interaction lands in HubSpot, Pipedrive, or your tool of choice — fully populated.",
  "fexp.f4.name": "Smart Quoting",
  "fexp.f4.body": "Mary drafts a real PDF estimate live on the call from your price book in under 60 seconds.",
  "fexp.f5.name": "AI Knowledge Base",
  "fexp.f5.body": "Pricing rules, install manuals, FAQs — Mary pulls answers straight from your docs.",
  "fexp.f6.name": "Data Analytics",
  "fexp.f6.body": "Dashboard tells you which channels close, which techs win, and what's leaking.",

  // FeatureExplorer demos
  "demo.chat.role": "Workflow Auth AI · WhatsApp",
  "demo.chat.in1": "Hi, my AC stopped cooling. Can someone come today?",
  "demo.chat.out1": "Yes — I have a tech 14 mins away. Same-day visit is $129 + parts. Confirm?",
  "demo.chat.in2": "Yes please.",
  "demo.chat.out2": "Booked for 4:20 PM. I've texted the tech's photo + ETA so you know who's at the door.",
  "demo.chat.pillBooked": "Booked · 4:20 PM",
  "demo.chat.pillEta": "Tech ETA sent",
  "demo.crm.title": "HubSpot · Auto-sync",
  "demo.crm.role": "Lead pushed in 2.1s",
  "demo.crm.contact": "Contact",
  "demo.crm.contactVal": "Demo Customer 001 · +1 (000) 123-4567",
  "demo.crm.source": "Source",
  "demo.crm.sourceVal": "Inbound Call · Vapi",
  "demo.crm.trade": "Trade",
  "demo.crm.tradeVal": "HVAC",
  "demo.crm.value": "Estimated value",
  "demo.crm.valueVal": "$12,300",
  "demo.crm.temp": "Temperature",
  "demo.crm.tempVal": "Hot",
  "demo.crm.owner": "Owner",
  "demo.crm.ownerVal": "Auto-assigned · Mary",
  "demo.crm.pillCreated": "Deal Created",
  "demo.crm.pillStage": "Stage: Quoted",
  "demo.quote.title": "Live Quote",
  "demo.quote.role": "Generated in 47s",
  "demo.quote.row1": "5× Standard PVC window 1.2 × 1.4m",
  "demo.quote.row2": "Removal & disposal",
  "demo.quote.row3": "Site survey + measurement",
  "demo.quote.totalLabel": "Total (incl. tax)",
  "demo.quote.pill": "Quote HL-A1F3C2 · sent",
  "demo.kb.title": "Knowledge Base",
  "demo.kb.role": "Answer pulled from your manuals",
  "demo.kb.in1": "My Liftmaster 8500 keeps reversing on close. Is that the safety sensor?",
  "demo.kb.out1": "Likely yes — that model uses a photo-eye sensor 6 inches off the ground. If it's misaligned or dusty, the door reverses. Try cleaning both lenses and check the LED is solid green.",
  "demo.kb.in2": "Still happening.",
  "demo.kb.out2": "I've booked our garage-door tech for tomorrow 9 AM. You'll get an SMS confirmation.",
  "demo.kb.pill": "Cited Liftmaster 8500 manual · §4.3",
  "demo.analytics.title": "This week",
  "demo.analytics.role": "Sept 23 – 29",
  "demo.analytics.s1n": "92%",
  "demo.analytics.s1l": "Calls answered < 2 rings",
  "demo.analytics.s2n": "$47.3k",
  "demo.analytics.s2l": "Quoted",
  "demo.analytics.s3n": "34%",
  "demo.analytics.s3l": "Quote → won rate",
  "demo.analytics.s4n": "23m",
  "demo.analytics.s4l": "Avg response time",
  "demo.analytics.pill": "+12% vs last week",

  // Mock dashboard
  "mock.crumb": "Overview",
  "mock.search": "Search…",
  "mock.kpi.leads": "Total Leads",
  "mock.kpi.leadsDelta": "+12% vs last 30d",
  "mock.kpi.quotes": "Quotes Generated",
  "mock.kpi.quotesDelta": "+8% acceptance",
  "mock.kpi.bookings": "Installations Booked",
  "mock.kpi.bookingsDelta": "+4 this week",
  "mock.section.title": "Recent Interactions",
  "mock.live": "Live",
  "mock.filter": "Filter",
  "mock.col.contact": "Contact",
  "mock.col.assistant": "Assistant",
  "mock.col.activity": "Activity",
  "mock.col.action": "Action",
  "mock.foot": "Showing 6 of 198",
  "mock.openReal": "Open the real dashboard",
  "mock.justNow": "Just now",
  "mock.secAgo": "{n}s ago",
  "mock.minAgo": "{n}m ago",
  "mock.hourAgo": "{n}h ago",
  "mock.channel.phone": "phone",
  "mock.channel.sms": "SMS",
  "mock.channel.whatsapp": "WhatsApp",
  "mock.channel.chat": "web chat",
  "mock.channel.email": "email",
  "mock.business": "Rolling Shutters Inc.",
  "mock.msg1": "Confirmed — proceed with the HVAC install for Tuesday.",
  "mock.msg2": "Need a quote on roof replacement, ~2,000 sq ft.",
  "mock.msg3": "Can someone come this Saturday morning?",
  "mock.msg4": "Do solar panels qualify for the new state rebate?",
  "mock.msg5": "Looking at the smart-thermostat package — what's included?",
  "mock.msg6": "When will my windows be delivered? Order #5521.",
  "mock.msg7": "Following up on the quote — happy to move forward.",
  "mock.msg8": "Drain still backing up after yesterday's visit.",

  "phoneWidget.incoming": "Incoming Call",
  "phoneWidget.frontDesk": "Mary · ABC Solar Co. front desk",
  "phoneWidget.decline": "Decline",
  "phoneWidget.accept": "Accept",
  "phoneWidget.answering": "Mary is answering…",
  "phoneWidget.t1": "Hello, I'd like to schedule a repair for my garage door.",
  "phoneWidget.t2": "I can help with that. Is it a motorised or manual door?",
  "phoneWidget.t3": "Motorised — Liftmaster, about 5 years old.",
  "phoneWidget.t4": "Got it. Saturday at 9 AM is open. Shall I book it in?",

  "pill.dealWon": "Deal Won",
  "pill.quoteSent": "Quote Sent",
  "pill.booked": "Booked",
  "pill.subsidy": "Subsidy Match",
  "pill.qualifying": "Qualifying",

  // LiveTicker
  "ticker.callsToday": "calls handled today",
  "ticker.i1": "Deal won · $12,300 HVAC install",
  "ticker.i2": "Quote drafted · $8,500 roof replacement",
  "ticker.i3": "HVAC lead qualified via SMS in 38s",
  "ticker.i4": "Saturday 9 AM booked · garage door repair",
  "ticker.i5": "Solar rebate match found · $2,400 saved",
  "ticker.i6": "Mary answered call · 02:14 duration",
  "ticker.i7": "Deal won · $9,450 window install",
  "ticker.i8": "Smart-thermostat add-on quoted · $1,200",
  "ticker.i9": "Burst-pipe emergency routed · tech ETA 22 min",
  "ticker.i10": "Tuesday 9:30 AM survey on the calendar",
  "ticker.i11": "5-window installation quote · drafted live",
  "ticker.i12": "Deal won · $4,820 furnace tune-up package",
  "ticker.i13": "Insulation grant matched · $1,800 covered",
  "ticker.i14": "Drainage estimate sent · $720 with site survey",
  "ticker.i15": "After-hours call qualified · routed to on-call",
  "ticker.i16": "Friday 11 AM roof leak quote booked",
  "ticker.i17": "WhatsApp lead → quote in 41 seconds",
  "ticker.i18": "Deal won · $18,900 full HVAC retrofit",

  // StatsBand
  "stats.eyebrow.short": "Why teams switch",
  "stats.title.short": "Every missed call is a job your competitor books.",
  "stats.body.short": "Workflow Auth picks up every inbound across every channel, qualifies it on the spot, and hands your crew a deal-ready conversation. Mary never sleeps and never takes a smoke break.",
  "stats.li1.short": "Calls answered while you're on a roof at 3 AM",
  "stats.li2.short": "Quotes drafted live on the call before you finish your coffee",
  "stats.li3.short": "Every interaction synced to HubSpot, Pipedrive, or your CRM",
  "stats.cardA.label": "of after-hours calls picked up — the ones your voicemail used to lose.",
  "stats.cardB.label": "average time from caller hello to a drafted estimate in your dashboard.",
  "stats.cardC.label": "average time-to-first-response across phone, SMS, and chat.",

  // Mobile apps band
  "apps.eyebrow": "Now on iPhone & Android",
  "apps.title": "Mary in your pocket.",
  "apps.body": "The Workflow Auth mobile apps put every lead, call and quote on your home screen. Tap a push, open the conversation, dispatch the crew. Built native — SwiftUI on iOS, Jetpack Compose on Android — against the same self-hostable backend.",
  "apps.f1.title": "Leads in your pocket",
  "apps.f1.body": "Mary's qualified leads sync to your phone the second they land — name, project, temperature, value.",
  "apps.f2.title": "Push the moment a job books",
  "apps.f2.body": "Tap a notification to jump straight into the customer's conversation. No noise, just signal.",
  "apps.f3.title": "View & edit AI-drafted quotes",
  "apps.f3.body": "Open Mary-drafted PDFs in-app, change status, edit notes, share with the customer.",
  "apps.f4.title": "Call transcripts on the go",
  "apps.f4.body": "Skim what Mary and the caller said, grouped by day. Catch up on yesterday's calls in two minutes.",
  "apps.appleTop": "Coming soon to the",
  "apps.appleBottom": "App Store",
  "apps.googleTop": "COMING SOON ON",
  "apps.googleBottom": "Google Play",
  "apps.note": "Self-hosting? Both apps point to your own backend via a single \"API URL\" setting in the app. One binary on the stores, your data on your server.",

  // ChatWidget
  "chat.intro": "Hi! I'm Mary from Workflow Auth. Need a quote, want to book a job, or have a question on a recent visit?",
  "chat.handoffIntro": "Connecting you to a human teammate — they'll see this conversation and reply here.",
  "chat.teaser.title": "Mary · Workflow Auth AI",
  "chat.teaser.body": "Hi! Need a quote or want to book? Ask me anything.",
  "chat.dismissTeaser": "Dismiss Mary teaser",
  "chat.openLabel": "Open Mary chat",
  "chat.closeLabel": "Close chat",
  "chat.role": "Workflow Auth AI · replies in seconds",
  "chat.placeholder": "Type a message…",
  "chat.send": "Send",
  "chat.quick.quote": "Get a quote",
  "chat.quick.book": "Book a visit",
  "chat.quick.subsidy": "Subsidy check",
  "chat.error.send": "Couldn't deliver that message — please try again in a moment.",
  "chat.error.closed": "This conversation is closed. Start a new one to keep talking.",
  "chat.script.q1": "Need a quote for 5 windows",
  "chat.script.a1a": "Got it — 5 windows. Are these standard PVC and around 1.2m × 1.4m?",
  "chat.script.a1b": "If yes, indicative price starts around $3,500 fitted.",
  "chat.script.q2": "Can someone come Saturday morning?",
  "chat.script.a2a": "I have Saturday at 9 AM open with our window team.",
  "chat.script.a2b": "Want me to lock that in and text you the confirmation?",
  "chat.script.q3": "Do solar panels qualify for the new state rebate?",
  "chat.script.a3a": "Yes — properties under $400k AV qualify for the 30% rebate this year.",
  "chat.script.a3b": "I can check your address and bundle the savings into your quote.",
  "chat.quick.human": "Talk to a human",
  "chat.live.support": "Workflow Auth Support",
  "chat.live.connected": "Connected to a human · live",
  "chat.live.connecting": "Connecting…",
  "chat.live.title": "Live chat",
  "chat.live.placeholder": "Message a human…",
  "chat.live.end": "End live chat",
  "chat.live.startNew": "Start a new chat",
  "chat.live.closedBanner": "This conversation is closed. Start a new chat to send another message.",
  "chat.live.unreachable": "We couldn't reach a human agent right now. Please try again shortly.",
  "chat.live.welcomeBack": "Welcome back — picking up where you left off.",
  "chat.live.backToAnna": "You're back with Mary. Want to ask something else?",
  "chat.intake.title": "Before we connect you",
  "chat.intake.sub": "So our team knows who they're talking to.",
  "chat.intake.name": "Name",
  "chat.intake.namePh": "Jane Doe",
  "chat.intake.email": "Email",
  "chat.intake.emailPh": "jane@example.com",
  "chat.intake.cancel": "Cancel",
  "chat.intake.submit": "Start chat",
  "chat.intake.submitting": "Connecting…",
  "chat.intake.errName": "Please enter your name.",
  "chat.intake.errEmail": "Please enter a valid email.",

  // AnnaDemoLauncher + Modal
  "annaLaunch.cta": "Hear Mary pick up",
  "annaModal.eyebrow": "Live demo · simulated call",
  "annaModal.title": "Watch Mary take a 3 AM emergency.",
  "annaModal.dialing": "Customer dialing in…",
  "annaModal.statusRinging": "Incoming call · ringing…",
  "annaModal.statusConnected": "Connected",
  "annaModal.statusEnded": "Call ended · summary saved to CRM",
  "annaModal.summaryTitle": "What just happened",
  "annaModal.summary1": "Lead qualified — emergency, no safety risk",
  "annaModal.summary2": "Tech booked · Tomorrow 7:45 AM",
  "annaModal.summary3": "Customer texted confirmation + tech name",
  "annaModal.summary4": "Deal created in HubSpot · #D-1042",
  "annaModal.foot": "This is a scripted preview. The real Mary runs on your business's own pricing, voice, and CRM.",
  "annaModal.bookReal": "Book a real demo",
  "annaModal.openSim": "Open the full simulator",
  "annaModal.line1": "Hi, this is Mary at Workflow Auth — how can I help tonight?",
  "annaModal.line2": "Yeah, my furnace just stopped working. It's freezing in here.",
  "annaModal.line3": "I'm sorry to hear that. Is there any smell or visible damage?",
  "annaModal.line4": "No smell. The pilot light is just out.",
  "annaModal.line5": "Got it. I can have a tech at your address by 7:45 AM. Shall I book it and text you the confirmation?",

  // /docs
  "docs.eyebrow": "Built in public · AGPL-3.0 · Self-hostable",
  "docs.title": "Self-host Workflow Auth.",
  "docs.sub": "Same dashboard, same AI pipeline, same code we ship in the YouTube build-alongs — yours under AGPL-3.0. Three commands and you're running the full stack locally.",
  "docs.tocStarted": "Get started",
  "docs.tocConcepts": "Concepts",
  "docs.tocIntegrations": "Integrations",
  "docs.tocProject": "Project",
  "docs.toc.quickstart": "Quick start",
  "docs.toc.architecture": "Architecture",
  "docs.toc.stack": "What's in the repo",
  "docs.toc.pipeline": "Mary's agent loop",
  "docs.toc.voice": "Wiring real voice",
  "docs.toc.demoData": "Seed demo data",
  "docs.toc.roadmap": "Roadmap",
  "docs.toc.license": "License",
  "docs.toc.starGh": "★ Star on GitHub",
  "docs.toc.buildAlong": "▶ Build along on YouTube",
  "docs.h.quickstart": "Quick start",
  "docs.h.architecture": "Architecture overview",
  "docs.h.stack": "What's in the repo",
  "docs.h.pipeline": "Mary's agent loop",
  "docs.h.voice": "Wiring real voice",
  "docs.h.demoData": "Seed demo data",
  "docs.h.roadmap": "Roadmap",
  "docs.h.license": "License",
  "docs.archP": "Three Docker services, two AI providers, one Postgres. The frontend renders server components against a Django REST API; voice runs through Vapi's custom-LLM mode so Mary keeps a real agent loop server-side.",
  "docs.arch.caller": "Caller",
  "docs.arch.callerSub": "Phone · SMS · WhatsApp · web chat · email",
  "docs.arch.vapi": "Vapi / Twilio",
  "docs.arch.vapiSub": "Voice handling, transcript per turn",
  "docs.arch.django": "Django + Mary",
  "docs.arch.djangoSub": "Claude tool loop, persists to Postgres",
  "docs.arch.next": "Next.js dashboard",
  "docs.arch.nextSub": "Server components, live KPIs, quote PDFs",
  "docs.stackP": "Every box below is wired up in code. Click the path to jump straight to the file on GitHub.",
  "docs.pipelineP": "Six stages, each one a single function, webhook, or tool dispatch in the codebase. Trace it with your IDE in five minutes.",
  "docs.voiceP1": "Drop your Vapi key in .env and point the assistant webhook at a tunnel of your local backend (or your deployed URL):",
  "docs.voiceP2.pre": "The custom-LLM completions endpoint lives at",
  "docs.voiceP2.post": " — Vapi POSTs the running transcript on every turn and Mary's loop returns the next utterance.",
  "docs.demoP": "One management command. Wipes the existing demo set and inserts 8 leads, 5 calls, 4 quotes — enough to see every dashboard view come alive.",
  "docs.roadmapP": "Pull requests welcome. Each line below is a real GitHub issue.",
  "docs.licenseP.pre": "The reference implementation is published under the ",
  "docs.licenseP.mid": ". A separate commercial license is available for white-labeling, reselling, or embedding Workflow Auth in closed-source products — email ",
  "docs.licenseP.post": ".",
  "docs.next.vapi": "Wire up Vapi",
  "docs.next.vapiSub": "Drop your key in .env and point a webhook.",
  "docs.next.seed": "Seed demo data",
  "docs.next.seedSub": "One command — the dashboard fills with believable rows.",
  "docs.next.deploy": "Deploy to a VPS",
  "docs.next.deploySub": "Docker Compose + Caddy auto-HTTPS in DEPLOY.md.",
  "docs.cloneCta": "★ Clone on GitHub",
  "docs.signinCta": "Sign in to dashboard",
  "docs.roadmap.shipped": "Shipped",
  "docs.roadmap.wip": "In progress",
  "docs.roadmap.todo": "Open issues",

  // FAQ
  "faq.heroEyebrow": "Frequently asked questions",
  "faq.heroT1": "Honest answers.",
  "faq.heroT2": "No marketing fluff.",
  "faq.heroSub": "Setup, pricing, integrations, security — the things home-service teams actually ask before signing up.",
  "faq.cat.all": "All",
  "faq.cat.setup": "Setup",
  "faq.cat.product": "Product",
  "faq.cat.pricing": "Pricing",
  "faq.cat.security": "Security",
  "faq.cat.oss": "Open source",
  "faq.finalT": "Still have a question?",
  "faq.finalSub": "Book a 30-minute call and ask directly.",

  // Contact page
  "contact.heroEyebrow": "Get in touch",
  "contact.heroT1": "Talk to a human.",
  "contact.heroT2": "Or send a ticket.",
  "contact.heroSub": "Demo bookings, self-host setup, partnership questions, or just feedback — pick the lane that fits and we'll get back to you.",
  "contact.ch1.title": "Book a 30-min call",
  "contact.ch1.body": "Walk through your setup, pricing, or self-host plan with Rashid (founder).",
  "contact.ch1.cta": "Open Calendly",
  "contact.ch2.title": "Email support",
  "contact.ch2.body": "Best for billing, deployments, or anything you'd rather not type into a form.",
  "contact.ch3.title": "Open an issue",
  "contact.ch3.body": "Bugs, feature requests, and architecture questions live on GitHub.",
  "contact.creatorRole": "Builds Workflow Auth live · @dropline",
  "contact.creatorBio": "AI build-along videos for developers shipping real agents. Hire me to deploy Workflow Auth for your business.",
  "contact.cardTitle": "Send a ticket",
  "contact.cardSub": "Average reply < 1 hour during business days. Tickets are saved to the dashboard and emailed to our team — we respond from promise@workflowauth.com.",
  "contact.f.name": "Your name",
  "contact.f.email": "Email",
  "contact.f.subject": "Subject",
  "contact.f.subjectPh": "What's this about?",
  "contact.f.body": "Message",
  "contact.f.bodyPh": "Describe your question or issue. The more detail, the faster we can help.",
  "contact.f.send": "Send ticket",
  "contact.f.sending": "Sending…",
  "contact.f.hint": "Or use the chat bubble for live help.",
  "contact.success.title": "Ticket received",
  "contact.success.again": "Submit another ticket",
  "contact.error.required": "Please fill in your name, email, and message.",
  "contact.error.email": "Please enter a valid email.",
  "contact.error.fallback": "Could not submit ticket. Please try again.",

  // Login
  "login.title": "Welcome back",
  "login.sub.pre": "Sign in to your Workflow Auth dashboard. Don't have an account? ",
  "login.sub.cta": "Book a demo",
  "login.email": "Email or username",
  "login.emailPh": "you@company.com",
  "login.password": "Password",
  "login.show": "Show",
  "login.hide": "Hide",
  "login.submit": "Sign in",
  "login.submitting": "Signing in…",
  "login.foot.pre": "Trouble signing in? Email ",
  "login.back": "← Back to home",
  "login.error.fallback": "Could not sign you in. Check your credentials.",
  "login.error.network": "Network error. Try again.",

  // MissedCallStory scene captions
  "story.scene.incoming": "Calling · 11:47 PM",
  "story.scene.calling": "calling",
  "story.scene.onLine": "on the line",
  "story.scene.transcript": "\"Hi, this is Mary with ABC Solar Co. I can help you tonight — what's going on at home?\"",
  "story.scene.calHead": "This week",
  "story.scene.calNew": "3 new bookings overnight",
  "story.scene.cal.survey": "5-window survey",
  "story.scene.cal.tagNew": "Mary · new",
  "story.scene.cal.hvac": "HVAC check-up",
  "story.scene.cal.roof": "Roof leak quote",
};

export function tEn(key: string): string {
  return en[key] ?? key;
}
