# Generated by Django 5.1.4 on 2026-06-25 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ticket',
            new_name='support_tic_busines_e24a77_idx',
            old_name='support_tic_busines_b00e2d_idx',
        ),
        migrations.RenameIndex(
            model_name='ticket',
            new_name='support_tic_channel_3bb229_idx',
            old_name='support_tic_channel_4f1a82_idx',
        ),
        migrations.RenameIndex(
            model_name='ticketmessage',
            new_name='support_tic_ticket__0cd9bd_idx',
            old_name='support_tic_ticket__27e9a3_idx',
        ),
        migrations.RenameIndex(
            model_name='ticketmessage',
            new_name='support_tic_provide_bee992_idx',
            old_name='support_tic_provide_3b7c04_idx',
        ),
    ]
