# Generated by Django 5.1.4 on 2026-04-29 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('vapi', 'Vapi'), ('twilio', 'Twilio')], max_length=16)),
                ('provider_call_id', models.CharField(db_index=True, max_length=128)),
                ('from_number', models.CharField(blank=True, max_length=32)),
                ('to_number', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(choices=[('ringing', 'Ringing'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('no_answer', 'No Answer')], default='ringing', max_length=16)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('recording_url', models.URLField(blank=True)),
                ('transcript', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='core.business')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', to='leads.lead')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
