# Generated by Django 5.2.1 on 2026-05-05 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='persona_used',
            field=models.CharField(blank=True, default='', help_text='Persona name active when this call was answered. Snapshot — survives later renames.', max_length=64),
        ),
    ]
