# Generated by Django 5.1.4 on 2026-06-25 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0002_persona_used'),
        ('core', '0012_business_do_not_call_business_followup_delay_hours_and_more'),
        ('leads', '0002_lead_leads_lead_busines_4fd20a_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboundTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('speed_to_lead', 'Speed to Lead'), ('follow_up', 'Follow-up'), ('reactivation', 'Reactivation'), ('reminder', 'Appointment Reminder')], max_length=20)),
                ('to_number', models.CharField(max_length=32)),
                ('objective', models.TextField(blank=True, help_text="Extra context for the agent's opening line.")),
                ('campaign', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('calling', 'Calling'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=12)),
                ('scheduled_for', models.DateTimeField(db_index=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=3)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_tasks', to='core.business')),
                ('call', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_tasks', to='calls.call')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_tasks', to='leads.lead')),
            ],
            options={
                'ordering': ['scheduled_for'],
                'indexes': [models.Index(fields=['business', 'status', 'scheduled_for'], name='calls_outbo_busines_d2be0c_idx')],
            },
        ),
    ]
